### ISSUE TITLE
error deploying sveltos with kustomization

### ISSUE THREAD

**Issue by MagnusRef** [projectsveltos/sveltos#203]
Hi

Im trying to use kustomization for installing sveltos in agentless mode with:
```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/projectsveltos/sveltos/v0.21.1/manifest/default-classifier.yaml
  - https://raw.githubusercontent.com/projectsveltos/sveltos/v0.21.1/manifest/agents_in_mgmt_cluster_manifest.yaml
```
However it will fail with the following:
```bash
kustomize build . --stack-trace
Error: accumulating resources: accumulation err='accumulating resources from 'https://raw.githubusercontent.com/projectsveltos/sveltos/v0.21.1/manifest/agents_in_mgmt_cluster_manifest.yaml': may not add resource with an already registered id: Namespace.v1.[noGrp]/
projectsveltos.[noNs]': failed to run '/usr/bin/git fetch --depth=1 https://raw.githubusercontent.com/projectsveltos/sveltos HEAD': remote: 404: Not Found
fatal: repository 'https://raw.githubusercontent.com/projectsveltos/sveltos/' not found
: exit status 128
```
It looks like that the namespace object `projectsveltos` is stated a whole 8 times in [agents_in_mgmt_cluster_manifest.yaml](https://github.com/projectsveltos/sveltos/blame/v0.21.1/manifest/agents_in_mgmt_cluster_manifest.yaml). and I think kustomization have some problems with that...

I have forked the repo and have been able to fix my issue by removing the multiple identical namespace objects in https://github.com/MagnusRef/sveltos/commit/351fc2ceb35602794368701efb0f070e36fa6ca4

**Comment by gianlucam76** [comment]
Thank you @MagnusRef
