### ISSUE TITLE
Install section

### ISSUE THREAD

**Issue by gianlucam76** [projectsveltos/sveltos#264]
Currently there are [two modes](https://projectsveltos.github.io/sveltos/getting_started/install/install/) to install Sveltos:
- Agent Installation Managed Cluster
- Agentless Installation Managed Cluster

Add a brief explanation of the differences between the two and one pick one vs the other.

**Comment by gianlucam76** [comment]
What do you think @egrosdou01? As new Sveltos user maybe there is not enough information on which installation mode to select.

**Comment by egrosdou01** [comment]
Hi Gianluca, it make sense to make it simpler for the end user. Let have a quick chat later today.
