### ISSUE TITLE
Templating: New Functions Available

### ISSUE THREAD

**Issue by gianlucam76** [projectsveltos/sveltos#292]
Extend template section by mentioning those extra methods are also available

https://github.com/projectsveltos/addon-controller/pull/586/files

**Comment by egrosdou01** [comment]
Action Items:
- Add the extra templating functions in the following page: https://projectsveltos.github.io/sveltos/template/template/
- Update the intro to template section. Keep logic and examples separate

**Comment by egrosdou01** [comment]
This is done. The issue can be closed.
