### ISSUE TITLE
show additional columns with kubectl

### ISSUE THREAD

**Issue by MagnusRef** [projectsveltos/sveltos#306]
Hello

It would be nice if it would be possible to show more information when doing a `kubectl get ...`.

For example having `k get clusterprofiles` show how many clusters are being matched, or `k get clustersummaries` showing the status eg. provisioned or provisioning.

Im am sure there are a lot of more useful additions, these are just the ones I feel like are missing.

**Comment by gianlucam76** [comment]
[This](https://github.com/projectsveltos/addon-controller/pull/615) prints status for ClusterSummary (it requires -o wide).

I could not find a way to print the length of an array with print column. It does not appear to be possible.

**Comment by gianlucam76** [comment]
Will be available in next release
