### ISSUE TITLE
Register an EKS cluster: Add documentation

### ISSUE THREAD

**Issue by gianlucam76** [projectsveltos/sveltos#354]
add a section covering [here](https://projectsveltos.github.io/sveltos/register/register-cluster/) on how to register an EKS cluster to be managed by Sveltos

**Comment by egrosdou01** [comment]
Working on it. A new PR will be available today.

**Comment by egrosdou01** [comment]
PR #355 was raised

**Comment by egrosdou01** [comment]
PR merged to main. The issue can be closed.
